# Generated by Django 4.2.5 on 2023-10-08 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_api', '0003_event_can_register_alter_event_background_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paye', models.BooleanField(default=False)),
                ('present_aller', models.BooleanField(default=False)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.event')),
            ],
        ),
    ]
