# Generated by Django 4.2.5 on 2023-12-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0009_remove_event_inscrits_inscription_sortie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('lieu',), 'verbose_name': 'Sortie', 'verbose_name_plural': 'Sorties'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='lieu',
        ),
        migrations.AlterField(
            model_name='event',
            name='logo_img',
            field=models.URLField(default='https://img.freepik.com/vecteurs-premium/creation-du-logo-station-ski_71835-128.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='nb_max',
            field=models.PositiveSmallIntegerField(default=63, verbose_name='Places disponibles'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prixA',
            field=models.PositiveSmallIntegerField(default=28, verbose_name='Prix Adhérent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prixNA',
            field=models.PositiveSmallIntegerField(default=37, verbose_name='Prix Non Adhérent'),
        ),
    ]
