# Generated by Django 4.2.5 on 2023-12-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_alter_membre_is_adherent_alter_membre_num_usca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ('user__last_name', 'user__first_name')},
        ),
    ]
