# Generated by Django 4.2.5 on 2023-12-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_membre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ('nom', 'prenom')},
        ),
        migrations.RemoveField(
            model_name='membre',
            name='is_adherent',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='num_usca',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='user',
        ),
        migrations.AddField(
            model_name='membre',
            name='ecole',
            field=models.CharField(choices=[('Polytech', 'Polytech'), ('IUT', 'IUT'), ('IAE', 'IAE'), ('exte', 'Exté')], default='Polytech', max_length=255, verbose_name='École'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='mail',
            field=models.EmailField(default='', max_length=255, unique=True, verbose_name='Adresse mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='nom',
            field=models.CharField(default='', max_length=255, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='prenom',
            field=models.CharField(default='', max_length=255, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membre',
            name='tel',
            field=models.CharField(max_length=255, verbose_name='Numéro de téléphone'),
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank='True', max_length=50, verbose_name='Numéro carte USCA')),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_api.membre')),
            ],
        ),
    ]
