# Generated by Django 4.2.5 on 2023-12-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_alter_membre_options_remove_membre_is_adherent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='numero',
            field=models.CharField(blank='True', max_length=50, unique=True, verbose_name='Numéro carte USCA'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='mail',
            field=models.EmailField(max_length=255, verbose_name='Adresse mail'),
        ),
    ]
