# Generated by Django 4.2.5 on 2023-10-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='is_adherent',
            field=models.BooleanField(default=False, verbose_name='Adhérent'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='num_usca',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro carte USCA'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='tel',
            field=models.CharField(max_length=12, verbose_name='Numéro de téléphone'),
        ),
    ]
