# Generated by Django 4.2.5 on 2023-12-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_alter_adhesion_numero_alter_membre_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='adherent',
            field=models.BooleanField(default=False, verbose_name='Adhérent'),
        ),
        migrations.DeleteModel(
            name='Adhesion',
        ),
    ]
