# Generated by Django 4.2.5 on 2024-01-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('desc', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('prix', models.FloatField()),
                ('image', models.URLField(max_length=500)),
            ],
        ),
    ]
