# Generated by Django 4.2.5 on 2024-01-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodie',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
