# Generated by Django 4.2.5 on 2024-01-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_membre_adherent_delete_adhesion'),
        ('shop_api', '0002_goodie_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('paye', models.BooleanField(default=False)),
                ('goodie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_api.goodie')),
                ('membre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_api.membre')),
            ],
        ),
    ]
