# Generated by Django 4.2.5 on 2023-10-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0002_event_background_img_event_logo_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='can_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='background_img',
            field=models.URLField(default='https://fr.newsonthesnow.com/news/wp-content/uploads/sites/3/2021/05/FR-Top-10-des-stations-de-ski-ide%CC%81ales-pour-un-week-end-hero-shutterstock-2-optimized.jpg', max_length=500),
        ),
    ]
