# Generated by Django 4.2.5 on 2023-10-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0004_remove_event_title_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='present_retour',
            field=models.BooleanField(default=False),
        ),
    ]
