# Generated by Django 4.2.5 on 2023-12-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0010_alter_event_options_rename_location_event_lieu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
