# Generated by Django 4.2.5 on 2023-12-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0011_alter_event_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',), 'verbose_name': 'Sortie', 'verbose_name_plural': 'Sorties'},
        ),
    ]
